name: Linter
on: [pull_request, push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: xt0rted/markdownlint-problem-matcher@v1
            - name: "Run Markdown linter"
              uses: docker://avtodev/markdown-lint:v1
              with:
                  args: docs/**/*.md
